# Application Name
spring.application.name=urent

# MongoDB Atlas URI (with authentication)
spring.data.mongodb.uri=mongodb+srv://u-rent:u-rent@u-rent.lly95.mongodb.net/urent

# Specify the database name
spring.data.mongodb.database=urent

# Enable MongoDB logging for debugging connection issues (optional)
logging.level.org.springframework.data.mongodb=DEBUG
