# Application Name
spring.application.name=urent

# MongoDB Atlas URI (with authentication)
spring.data.mongodb.uri=mongodb+srv://u-rent:u-rent@u-rent.lly95.mongodb.net/
# spring.data.mongodb.uri=mongodb://localhost:27017/3010
# Specify the database name
spring.data.mongodb.database=u-rent

# Enable MongoDB logging for debugging connection issues (optional)
logging.level.org.springframework.data.mongodb=DEBUG
server.port=8090
# Replace with a valid 256-bit secret key
jwt.secret=M0FDQjlGM0Q1RTdCOEM2QTFGNEQyQjlDOEUzQTdGNUQzQUNCOUYzRDVFN0I4QzJBMUY0RDZCOUNDOEUzQTdGNUQ=
jwt.expiration=86400
logging.level.org.springframework.beans=DEBUG
logging.level.org.springframework.context=DEBUG
logging.level.org.springframework.security=DEBUG
spring.cache.type=none
# Enable detailed error messages
server.error.include-message=always
server.error.include-stacktrace=always

# Enable debug logging for Spring Security and your application
# logging.level.org.springframework.security=DEBUG
logging.level.com.urent.urent=DEBUG